version: '3'
services:
  app:
    build:
      context: .
      args:
        GID: ${GROUP_ID}
        UID: ${USER_ID}
    image: 'mirrors/homebrew:0.0.1'
    command: ['bash']
    tty: true
    stdin_open: true
    volumes:
      - '.:/home/mobydick/app'
